#!/usr/bin/env bash
# privacy-hygiene optout.sh
# Modes: --detect (report installed telemetry-bearing tools)
#        --apply  (write opt-out file, wire into shell rc, run per-tool commands)
#        --verify (confirm vars resolve in a fresh login shell)
#        --undo   (remove the env-var opt-out layer; list per-tool reversals)
# Idempotent. Writes only: ~/.config/privacy-hygiene/telemetry-optout.sh,
# one guarded source line per existing shell rc, and per-tool config stores.
# Per-tool commands and the VS Code recommendation are NOT reverted by --undo
# (re-enabling telemetry silently would be a surprising change); --undo lists them.
set -euo pipefail

OPTOUT_DIR="${HOME}/.config/privacy-hygiene"
OPTOUT_FILE="${OPTOUT_DIR}/telemetry-optout.sh"
MARKER="# >>> privacy-hygiene telemetry opt-out >>>"
END_MARKER="# <<< privacy-hygiene telemetry opt-out <<<"

# KEEP IN SYNC with references/telemetry-optouts.md (env var table).
ENV_VARS=(
  "DO_NOT_TRACK=1"
  "DOTNET_CLI_TELEMETRY_OPTOUT=1"
  "POWERSHELL_TELEMETRY_OPTOUT=1"
  "NEXT_TELEMETRY_DISABLED=1"
  "NUXT_TELEMETRY_DISABLED=1"
  "GATSBY_TELEMETRY_DISABLED=1"
  "ASTRO_TELEMETRY_DISABLED=1"
  "STORYBOOK_DISABLE_TELEMETRY=1"
  "TURBO_TELEMETRY_DISABLED=1"
  "EXPO_NO_TELEMETRY=1"
  "GEMINI_TELEMETRY_ENABLED=false"
  "NG_CLI_ANALYTICS=false"
  "SCARF_ANALYTICS=false"
  "HOMEBREW_NO_ANALYTICS=1"
  "CHECKPOINT_DISABLE=1"
  "AZURE_CORE_COLLECT_TELEMETRY=0"
  "SAM_CLI_TELEMETRY=0"
  "STRIPE_CLI_TELEMETRY_OPTOUT=1"
  "WRANGLER_SEND_METRICS=false"
  "SF_DISABLE_TELEMETRY=true"
  "SFDX_DISABLE_TELEMETRY=true"
  "SLS_TELEMETRY_DISABLED=1"
  "FASTLANE_OPT_OUT_USAGE=1"
  "HASURA_GRAPHQL_ENABLE_TELEMETRY=false"
  "STRAPI_TELEMETRY_DISABLED=true"
  "MELTANO_SEND_ANONYMOUS_USAGE_STATS=False"
  "INFLUXD_REPORTING_DISABLED=true"
  "RASA_TELEMETRY_ENABLED=false"
  "EARTHLY_DISABLE_ANALYTICS=true"
  "PANTS_ANONYMOUS_TELEMETRY_ENABLED=false"
  "SEMGREP_SEND_METRICS=off"
  "GRYPE_CHECK_FOR_APP_UPDATE=false"
  "SYFT_CHECK_FOR_APP_UPDATE=false"
  "TRIVY_SKIP_VERSION_CHECK=true"
  "DISABLE_TELEMETRY=1"
  "DISABLE_ERROR_REPORTING=1"
  "DISABLE_FEEDBACK_COMMAND=1"
  "CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1"
)

# tool|command|verify  -- run only when the tool binary is on PATH.
# verify=1 marks a mechanism known to drift between versions (see catalog).
# KEEP IN SYNC with references/telemetry-optouts.md (per-tool command table).
TOOL_COMMANDS=(
  "brew|brew analytics off|0"
  "go|go telemetry off|0"
  "dart|dart --disable-analytics|0"
  "flutter|flutter config --no-analytics|1"
  "vercel|vercel telemetry disable|0"
  "netlify|netlify --telemetry-disable|1"
  "ionic|ionic config set --global telemetry false|0"
  "cordova|cordova telemetry off|0"
  "dvc|dvc config --global core.analytics false|0"
  "yarn|yarn config set --home enableTelemetry 0|0"
  "gcloud|gcloud config set disable_usage_reporting true|0"
  "gh|gh config set telemetry disabled|1"
)

TELEMETRY_TOOLS=(dotnet pwsh brew terraform packer vagrant az sam stripe wrangler sf sfdx serverless fastlane go dart flutter vercel netlify ionic cordova dvc yarn gcloud gh gemini semgrep grype syft trivy code claude)

# Shell rc files we wire the source line into, when they exist. Login and
# interactive variants are both covered so macOS bash login shells (.bash_profile)
# and zsh login shells (.zprofile) pick up the opt-out. Double-sourcing is
# idempotent (re-export only).
RC_FILES=(
  "${HOME}/.bashrc"
  "${HOME}/.bash_profile"
  "${HOME}/.zshrc"
  "${HOME}/.zprofile"
  "${HOME}/.profile"
)

detect() {
  echo "== Installed telemetry-bearing tools =="
  local found=0 t
  for t in "${TELEMETRY_TOOLS[@]}"; do
    if command -v "$t" >/dev/null 2>&1; then
      printf "  %-12s %s\n" "$t" "$(command -v "$t")"
      found=1
    fi
  done
  [[ $found -eq 0 ]] && echo "  (none detected on PATH)"
  echo
  if [[ -f "$OPTOUT_FILE" ]]; then
    echo "Opt-out file present: $OPTOUT_FILE"
  else
    echo "Opt-out file not yet created."
  fi
}

apply() {
  mkdir -p "$OPTOUT_DIR"
  {
    echo "# Generated by privacy-hygiene skill. Remove with: optout.sh --undo"
    echo "# (deletes this file and the rc source lines; per-tool settings stay)."
    echo "# Regenerated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    local kv
    for kv in "${ENV_VARS[@]}"; do
      echo "export ${kv}"
    done
  } > "$OPTOUT_FILE"
  echo "Wrote ${#ENV_VARS[@]} opt-outs to $OPTOUT_FILE"

  local rc
  for rc in "${RC_FILES[@]}"; do
    [[ -f "$rc" ]] || continue
    if ! grep -qF "$MARKER" "$rc"; then
      {
        echo ""
        echo "$MARKER"
        echo "[ -f \"$OPTOUT_FILE\" ] && . \"$OPTOUT_FILE\""
        echo "$END_MARKER"
      } >> "$rc"
      echo "Wired into $rc"
    else
      echo "Already wired into $rc"
    fi
  done

  echo
  echo "== Per-tool config commands =="
  local entry tool cmd vflag
  for entry in "${TOOL_COMMANDS[@]}"; do
    IFS='|' read -r tool cmd vflag <<< "$entry"
    if command -v "$tool" >/dev/null 2>&1; then
      echo "  running: $cmd"
      if eval "$cmd" >/dev/null 2>&1; then
        echo "    ok"
      elif [[ "$vflag" == "1" ]]; then
        echo "    FAILED (mechanism marked (verify); may have changed in this version)"
      else
        echo "    FAILED (verify manually)"
      fi
    fi
  done

  echo
  echo "== VS Code telemetry (advisory) =="
  vscode_advise
  echo
  echo "Done. Open a new shell or: source $OPTOUT_FILE"
}

# Report VS Code telemetry state without rewriting settings.json (rewriting
# would strip comments and reformat). Detection tolerates JSONC.
vscode_advise() {
  local vsdir settings
  local any=0
  for vsdir in "${HOME}/.config/Code/User" "${HOME}/Library/Application Support/Code/User" "${HOME}/.config/VSCodium/User"; do
    settings="${vsdir}/settings.json"
    [[ -f "$settings" ]] || continue
    any=1
    if command -v python3 >/dev/null 2>&1; then
      python3 - "$settings" <<'PYEOF' || true
import json, re, sys
p = sys.argv[1]
raw = open(p, encoding="utf-8", errors="replace").read()
# strip // line comments and /* */ block comments, then trailing commas
s = re.sub(r'//[^\n]*', '', raw)
s = re.sub(r'/\*.*?\*/', '', s, flags=re.S)
s = re.sub(r',(\s*[}\]])', r'\1', s)
try:
    data = json.loads(s)
except Exception:
    print(f"  {p}: could not parse; add  \"telemetry.telemetryLevel\": \"off\"  manually")
    sys.exit(0)
level = data.get("telemetry.telemetryLevel")
if level == "off":
    print(f"  {p}: already off")
else:
    cur = "unset" if level is None else repr(level)
    print(f"  {p}: telemetry is {cur}; add  \"telemetry.telemetryLevel\": \"off\"")
PYEOF
    else
      echo "  $settings present; set telemetry.telemetryLevel to off (python3 not available to inspect)"
    fi
  done
  [[ $any -eq 0 ]] && echo "  no VS Code/VSCodium settings.json found"
}

verify() {
  if [[ ! -f "$OPTOUT_FILE" ]]; then
    echo "No opt-out file; run --apply first."; exit 1
  fi
  echo "== Verifying opt-outs resolve in a fresh interactive shell =="
  local tested=0 total_fail=0 pair file shbin
  for pair in "${HOME}/.bashrc:bash" "${HOME}/.zshrc:zsh"; do
    file="${pair%:*}"; shbin="${pair##*:}"
    { [[ -f "$file" ]] && grep -qF "$MARKER" "$file"; } || continue
    if ! command -v "$shbin" >/dev/null 2>&1; then
      echo "  ($shbin wired in $file but $shbin not installed; skipping)"
      continue
    fi
    tested=1
    local oks=0 kv var want got
    for kv in "${ENV_VARS[@]}"; do
      var="${kv%%=*}"; want="${kv#*=}"
      got="$("$shbin" -ic "echo \${$var:-UNSET}" 2>/dev/null | tail -n1)"
      if [[ "$got" == "$want" ]]; then
        oks=$((oks+1))
      else
        printf "  MISS  %-32s (got: %s) via %s\n" "$var" "$got" "$shbin"
        total_fail=$((total_fail+1))
      fi
    done
    echo "  $oks/${#ENV_VARS[@]} resolved via $shbin ($file)"
  done

  if [[ $tested -eq 0 ]]; then
    echo "  No wired interactive shell available; sourcing opt-out file directly."
    local oks=0 kv var want got
    set +u
    # shellcheck source=/dev/null
    . "$OPTOUT_FILE"
    set -u
    for kv in "${ENV_VARS[@]}"; do
      var="${kv%%=*}"; want="${kv#*=}"; got="${!var:-UNSET}"
      if [[ "$got" == "$want" ]]; then oks=$((oks+1))
      else printf "  MISS  %-32s (got: %s)\n" "$var" "$got"; total_fail=$((total_fail+1)); fi
    done
    echo "  $oks/${#ENV_VARS[@]} resolved from $OPTOUT_FILE"
  fi

  echo
  [[ $total_fail -eq 0 ]] && echo "All opt-outs resolve." || echo "$total_fail check(s) failed; review shell rc ordering."
}

undo() {
  echo "== Removing env-var opt-out layer =="
  local rc removed=0
  for rc in "${RC_FILES[@]}"; do
    [[ -f "$rc" ]] || continue
    if grep -qF "$MARKER" "$rc"; then
      local tmp; tmp="$(mktemp)"
      awk -v s="$MARKER" -v e="$END_MARKER" '
        $0==s {skip=1; next}
        skip==1 {if ($0==e) skip=0; next}
        {print}
      ' "$rc" > "$tmp" && mv "$tmp" "$rc"
      echo "  removed opt-out block from $rc"
      removed=1
    fi
  done
  [[ $removed -eq 0 ]] && echo "  no rc blocks found"
  if [[ -f "$OPTOUT_FILE" ]]; then rm -f "$OPTOUT_FILE"; echo "  removed $OPTOUT_FILE"; fi

  echo
  echo "Env-var opt-outs removed. Per-tool settings were left as-is on purpose."
  echo "To re-enable telemetry for tools you no longer want opted out, reverse these"
  echo "by hand (consult each tool's docs):"
  local entry tool cmd vflag
  for entry in "${TOOL_COMMANDS[@]}"; do
    IFS='|' read -r tool cmd vflag <<< "$entry"
    command -v "$tool" >/dev/null 2>&1 || continue
    echo "  $tool   (you ran: $cmd)"
  done
  echo "  VS Code: remove or change telemetry.telemetryLevel in settings.json if you set it."
}

case "${1:---detect}" in
  --detect) detect ;;
  --apply)  apply ;;
  --verify) verify ;;
  --undo)   undo ;;
  *) echo "Usage: $0 [--detect|--apply|--verify|--undo]"; exit 1 ;;
esac
